AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Stack for Summarization Pipeline"

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/s3.template.yaml"
      Parameters:
        BucketName: !Ref S3BucketName

  SSMParameterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/ssm.template.yaml"
      Parameters:
        BucketName: !Ref S3BucketName
        RawFilesPrefix: !Ref RawFilesPrefix
        ProcessedFilesPrefix: !Ref ProcessedFilesPrefix

  TextractPipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/textract.template.yml"
      Parameters:
        BucketName: !Ref S3BucketName

Parameters:
  BucketName:
    Type: String
    Default: "cs-helper"
    Description: "The name of the S3 bucket"
  
  RawFilesPrefix:
    Type: String
    Default: "summarization-raw-files/"
    Description: "Prefix for raw files in S3 bucket"

  ProcessedFilesPrefix:
    Type: String
    Default: "summarization-processed-files/"
    Description: "Prefix for processed files in S3 bucket"
