AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Stack for Summarization Pipeline"

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "The name of the S3 bucket"

  RawFilesPrefix:
    Type: String
    Default: "summarization-raw-files/"
    Description: "Prefix for raw files in S3 bucket"

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/s3.template.yml"
      Parameters:
        BucketName: !Ref BucketName

  TextractPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/textract.template.yml"
      Parameters:
        BucketName: !Ref BucketName
        RawFilesPrefix: !Ref RawFilesPrefix
