AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Stack for Summarization Pipeline"

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "The name of the s3 bucket"
    Default: BucketName

  RawFilesPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Prefix of the folder where raw files are stored"
    Default: RawFilesPrefix

  ToBeProcessedFilesPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Prefix of the folder where processed files are stored"
    Default: ToBeProcessedFilesPrefix

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/s3.template.yml"
      Parameters:
        BucketName: !Ref BucketName
        RawFilesPrefix: !Ref RawFilesPrefix
        ToBeProcessedFilesPrefix: !Ref ToBeProcessedFilesPrefix


  TextractPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/textract.template.yml"
      Parameters:
        BucketName: !Ref BucketName
        RawFilesPrefix: !Ref RawFilesPrefix
        ToBeProcessedFilesPrefix: !Ref ToBeProcessedFilesPrefix
