AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Stack for Summarization Pipeline"

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "The name of the S3 bucket"
  
  RawFilesPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Prefix for raw files in S3 bucket"

  ProcessedFilesPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Prefix for processed files in S3 bucket"

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/s3.template.yaml"
      Parameters:
        BucketName: !Ref BucketName

  # SSMParameterStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: S3BucketStack  # Ensure S3 stack is created first
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/ssm.template.yaml"
  #     Parameters:
  #       BucketName: !Ref BucketName
  #       RawFilesPrefix: !Ref RawFilesPrefix
  #       ProcessedFilesPrefix: !Ref ProcessedFilesPrefix

  TextractPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketStack  # Ensure SSM stack is created before Textract
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${BucketName}/template/textract.template.yml"
      Parameters:
        BucketName: !Ref BucketName
