AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Buckets Template for Summarization Pipeline"

Parameters:
  BucketName:
    Type: String
    Default: "cs-helper"
    Description: "The name of the S3 bucket"

Conditions:
  BucketDoesNotExist: !Not [!Equals [!Ref BucketName, ""]]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: BucketDoesNotExist
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: "Name of the created or existing S3 bucket"
    Value: !Ref BucketName
