AWSTemplateFormatVersion: "2010-09-09"
Description: "SSM Parameter Store Template for Summarization Pipeline"

Parameters:
  BucketName:
    Type: String
    Default: "cs-helper"
    Description: "The name of the s3 bucket"

  RawFilesPrefix:
    Type: String
    Default: "summarization-raw-files/"
    Description: "Prefix of the folder where raw files are stored"

  ToBeProcessedFilesPrefix:
    Type: String
    Default: "summarization-to-be-processed-files/"
    Description: "Prefix of the folder where to be processed files are stored"

  ProcessedFilesPrefix:
    Type: String
    Default: "summarization-processed-files/"
    Description: "Prefix of the folder where processed files are stored"


Resources:
  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BucketName
      Type: String
      Value: !Ref BucketName

  RawFilesPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: RawFilesPrefix
      Type: String
      Value: !Ref RawFilesPrefix

  
  ToBeProcessedFilesPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ToBeProcessedFilesPrefix
      Type: String
      Value: !Ref ToBeProcessedFilesPrefix

  
  ProcessedFilesPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ProcessedFilesPrefix
      Type: String
      Value: !Ref ProcessedFilesPrefix

  