AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function with S3 trigger setup for an existing bucket."

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"

  RawFilesPrefix:
    Type: String
    Description: "Prefix for raw files in the S3 bucket"

Resources:
  # IAM Role for Lambda
  TextractLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # Lambda Function
  TextractLambda:
    Type: AWS::Lambda::Function
    DependsOn: TextractLambdaRole
    Properties:
      FunctionName: "TextractProcessingLambda"
      Runtime: python3.8
      Handler: textract_lambda.handler
      Role: !GetAtt TextractLambdaRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "textract_lambda.zip"
      Timeout: 120
      MemorySize: 512

  # Lambda Permission for S3 Invocation
  TextractLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: TextractLambda
    Properties:
      FunctionName: !GetAtt TextractLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"

  # Bucket Notification for Existing S3 Bucket
  TextractBucketNotification:
    Type: AWS::S3::BucketNotification
    DependsOn: TextractLambdaPermission
    Properties:
      Bucket: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: "prefix"
                    Value: !Ref RawFilesPrefix
            Function: !GetAtt TextractLambda.Arn

Outputs:
  LambdaFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref TextractLambda
