AWSTemplateFormatVersion: "2010-09-09"
Description: "Textract Processing Pipeline"

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"

  RawFilesPrefix:
    Type: String
    Description: "Prefix for raw files in S3 bucket"

Resources:

  # IAM Role for Lambda with Textract permissions
  TextractLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TextractAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "textract:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:*:*:parameter/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - "events:PutTargets"
                  - "events:PutRule"
                  - "events:DeleteRule"
                Resource: "*"

  # Lambda Function
  TextractLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "TextractProcessingLambda"
      Runtime: python3.8
      Handler: textract_lambda.handler
      Role: !GetAtt TextractLambdaRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "textract_lambda.zip"
      Timeout: 120
      MemorySize: 512

  # Lambda Permission for S3 Invocation
  TextractLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TextractLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"

  # EventBridge Rule for S3 Uploads
  S3EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "S3UploadEventRule"
      Description: "Triggers Textract Lambda when a file is uploaded to the S3 bucket with a specific prefix."
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref BucketName
          object:
            key:
              prefix:
                - !Ref RawFilesPrefix
      Targets:
        - Arn: !GetAtt TextractLambda.Arn
          Id: "TextractLambdaTarget"
