AWSTemplateFormatVersion: "2010-09-09"
Description: "Textract Processing Pipeline"

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"

  RawFilesPrefix:
    Type: String
    Description: "Prefix for raw files in S3 bucket"

Resources:

  # IAM Role for Textract Lambda
  TextractLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TextractAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "textract:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:*:*:parameter/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # Textract Lambda Function
  TextractLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "TextractProcessingLambda"
      Runtime: python3.8
      Handler: textract_lambda.handler
      Role: !GetAtt TextractLambdaRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "textract_lambda.zip"
      Timeout: 120
      MemorySize: 512

  # IAM Role for Notification Lambda
  NotificationLambdaRole:
    Type: AWS::IAM::Role
    DependsOn: TextractLambda  # Ensure TextractLambda is created first
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketNotification"
                  - "s3:PutBucketNotification"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: "arn:aws:s3:::${BucketName}/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # Notification Lambda Function
  NotificationLambda:
    Type: AWS::Lambda::Function
    DependsOn: TextractLambdaRole  # Ensure IAM role for NotificationLambda is created after TextractLambdaRole
    Properties:
      FunctionName: "NotificationLambda"
      Runtime: python3.8
      Handler: index.handler
      Role: !GetAtt NotificationLambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          def handler(event, context):
              s3 = boto3.client('s3')
              bucket_name = event['ResourceProperties']['BucketName']
              lambda_arn = event['ResourceProperties']['LambdaArn']
              prefix = event['ResourceProperties']['Prefix']
              try:
                  # Get current notification configuration
                  current_config = s3.get_bucket_notification_configuration(Bucket=bucket_name)
                  current_config.pop("ResponseMetadata", None)

                  # Add Lambda trigger
                  current_config.setdefault('LambdaFunctionConfigurations', []).append({
                      'LambdaFunctionArn': lambda_arn,
                      'Events': ['s3:ObjectCreated:*'],
                      'Filter': {
                          'Key': {
                              'FilterRules': [{'Name': 'prefix', 'Value': prefix}]
                          }
                      }
                  })

                  # Apply new notification configuration
                  s3.put_bucket_notification_configuration(
                      Bucket=bucket_name,
                      NotificationConfiguration=current_config
                  )
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Message': str(e)})

  # Custom Resource to Set S3 Notification
  S3NotificationConfiguration:
    Type: Custom::S3Notification
    DependsOn: NotificationLambda  # Ensure Notification Lambda is created first
    Properties:
      ServiceToken: !GetAtt NotificationLambda.Arn
      BucketName: !Ref BucketName
      LambdaArn: !GetAtt TextractLambda.Arn
      Prefix: !Ref RawFilesPrefix

Outputs:
  TextractLambdaArn:
    Description: "ARN of the Textract Lambda Function"
    Value: !GetAtt TextractLambda.Arn
