name: Deploy Summarization Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda Function
      run: |
        # Package Lambda code only, without dependencies
        cd lambda
        zip -r9 ../textract_lambda.zip ./*
        mv ../textract_lambda.zip ../scripts/
        cd ..

    
    - name: Create Lambda Layer for Spacy
      run: |
        mkdir -p layer/python
        pip install --no-deps spacy==3.8.3 -t layer/python/
        pip install preshed blis murmurhash cymem thinc numpy -t layer/python/
        python3 -m spacy download en_core_web_sm
        cp -r $(python3 -c "import en_core_web_sm; print(en_core_web_sm.__path__[0])") layer/python/en_core_web_sm

        # Remove unnecessary files
        find layer/python -name "__pycache__" -type d -exec rm -r {} +
        find layer/python -name "*.dist-info" -type d -exec rm -r {} +
        find layer/python -name "tests" -type d -exec rm -r {} +

        # Create the layer package
        cd layer
        zip -r9 ../spacy_lambda_layer.zip ./*
        cd ..
        aws s3 cp spacy_lambda_layer.zip s3://cs-helper/spacy_lambda_layer.zip

        # Clean up
        rm -rf layer spacy_lambda_layer.zip



    - name: Create Lambda Layer for General Dependencies
      run: |
        mkdir -p layer/python
        pip install -r lambda/requirements.txt -t layer/python/
        
        # Remove unnecessary files
        find layer/python -name "__pycache__" -type d -exec rm -r {} +
        find layer/python -name "*.dist-info" -type d -exec rm -r {} +
        find layer/python -name "tests" -type d -exec rm -r {} +

        cd layer
        zip -r9 ../general_lambda_layer.zip ./*
        cd ..
        aws s3 cp general_lambda_layer.zip s3://cs-helper/general_lambda_layer.zip

        # Clean up
        rm -rf layer general_lambda_layer.zip

    - name: Deploy SSM Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/ssm.template.yml \
          --stack-name SSMParameterStack \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Upload YAML templates and Lambda package to S3
      run: |
        aws s3 cp scripts/textract_lambda.zip s3://cs-helper/textract_lambda.zip
        aws s3 cp templates/s3.template.yml s3://cs-helper/template/
        aws s3 cp templates/ssm.template.yml s3://cs-helper/template/
        aws s3 cp templates/textract.template.yml s3://cs-helper/template/
        aws s3 cp templates/master-stack.template.yml s3://cs-helper/template/

    - name: Deploy Master Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/master-stack.template.yml \
          --stack-name SummarizationMasterStack \
          --capabilities CAPABILITY_NAMED_IAM
