name: Deploy Summarization Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda Function
      run: |
        cd lambda
        zip -r textract_lambda.zip ./*
        mv textract_lambda.zip ../scripts/
        cd ..

    - name: Upload YAML templates to S3
      run: |
        aws s3 cp scripts/textract_lambda.zip s3://cs-helper/textract_lambda.zip
        aws s3 cp templates/s3.template.yaml s3://cs-helper/template/
        aws s3 cp templates/ssm.template.yaml s3://cs-helper/template/
        aws s3 cp templates/textract.template.yml s3://cs-helper/template/
        aws s3 cp templates/master-stack.template.yml s3://cs-helper/template/

    - name: Deploy Master Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/master-stack.template.yml \
          --stack-name SummarizationMasterStack \
          --parameter-overrides \
            BucketName="cs-helper" \
            RawFilesPrefix="summarization-raw-files/" \
            ProcessedFilesPrefix="summarization-processed-files/" \
          --capabilities CAPABILITY_NAMED_IAM
