name: Deploy Summarization Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Dependencies and Package Lambda
      run: |
        # Create a directory for the deployment package
        mkdir -p scripts
        cd lambda

        # Install dependencies into the Lambda directory
        pip install -r requirements.txt -t ./

        # Clean unnecessary files
        find . -name "__pycache__" -type d -exec rm -r {} +
        find . -name "*.dist-info" -type d -exec rm -r {} +
        find . -name "tests" -type d -exec rm -r {} +

        # Create the deployment package
        zip -r9 ../scripts/textract_lambda.zip ./*

        cd ..

    - name: Deploy SSM Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/ssm.template.yml \
          --stack-name SSMParameterStack \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Upload YAML templates and Lambda package to S3
      run: |
        aws s3 cp scripts/textract_lambda.zip s3://cs-helper/textract_lambda.zip
        aws s3 cp templates/s3.template.yml s3://cs-helper/template/
        aws s3 cp templates/ssm.template.yml s3://cs-helper/template/
        aws s3 cp templates/textract.template.yml s3://cs-helper/template/
        aws s3 cp templates/master-stack.template.yml s3://cs-helper/template/

    - name: Deploy Master Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/master-stack.template.yml \
          --stack-name SummarizationMasterStack \
          --capabilities CAPABILITY_NAMED_IAM
